version: '3.6'

services: 
  mariadb:
    container_name: mariadb-use-volume-test
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PW}
    volumes: 
      - ${HOME}/${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${HOME}/${MYSQL_CONFIG_PATH}:/etc/mysql/conf.d
    # networks: 
    #   - study-proxy

  nginx:
    container_name: nginx-use-volume-test
    image: nginx:latest
    restart: always
    # environment: 
    #   - NGINX_HOST=mongmong.p-e.kr
    #   - NGINX_PORT=3000
    ports: 
      - 80:80
      # - 443:443
    # volumes: 
      # - ${HOME}/${NGINX_DEFAULT_CONFIG}:/etc/nginx/conf.d/default.conf.template
      # - ${HOME}/${NGINX_VHOSTS}:/etc/nginx/conf.d/vhosts.conf
    # networks: 
    #   - study-proxy
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx-docker-setting > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

networks:
  default:
    external: 
      name: ${DOCKER_NETWORK_NAME_CONFIG}